security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            host:       "%main_host%"
            security:   false

        api:
            pattern:    ^/
            host:       "%api_host%"
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

        main:
            pattern: ^/
            host:    "%main_host%"
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, host: "%main_host%", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, host: "%main_host%", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, host: "%main_host%", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, host: "%main_host%", role: ROLE_ADMIN }
        - { path: ^/, host: "%api_host%", roles: [ IS_AUTHENTICATED_FULLY ] }